### ISSUE TITLE
Output ports not properly displayed when they go to multiple components

### ISSUE THREAD

**Issue by MireilleSchneider** [DaanVanVugt/ymmsl-dot#1]
I have a ymssl file for which the 'im_workflow' component has O_I ports that go to multiple other components of the workflow. In this case, not all arrows are displayed as exiting from the O_I port, so it looks like a display error in this context. Can you please fig it? I  have attached the ymmsl file and the resulting figure.

![ymmsl_dot_output](https://user-images.githubusercontent.com/31791919/233577436-8bef49a7-aba5-48b0-ac9e-4c1e412387fa.PNG)

[coupling.txt](https://github.com/DaanVanVugt/ymmsl-dot/files/11293580/coupling.txt)

```
ymmsl_version: v0.1

model:
  name: imas_pcssp_prototype

  components:
  
    im_workflow:
      implementation: im_workflow
      ports:
        s: [core_profiles_in]
        o_i: [core_profiles_out,equilibrium_out,interferometer_out]

    smart:
      implementation: smart
      ports:
        f_init: [equilibrium_in,core_profiles_in,pellets_in]
        o_f: [core_profiles_out]

    tip:
      implementation: tip
      ports:
        f_init: [equilibrium_in, core_profiles_in, interferometer_in]
        o_f: [interferometer_out]

    imas_rt_mapping:
      implementation: imas_rt_mapping
      ports:
        # Without PCSSP
        f_init: [interferometer_in]
        o_f: [pellets_out]
        # To be added with PCSSP:
        o_i: [line_avg_density_out]
        s: [pellets_trigger_request_in]

    pelletController:
      implementation: pelletController
      ports:
        s: [line_avg_density_in]
        o_i: [pellets_trigger_request_out]  

  conduits:
  
    # From IM workflow
    im_workflow.core_profiles_out:
    - tip.core_profiles_in
    - smart.core_profiles_in
    im_workflow.equilibrium_out:
    - tip.equilibrium_in
    - smart.equilibrium_in
    im_workflow.interferometer_out: tip.interferometer_in
    
    # From SMART
    smart.core_profiles_out: im_workflow.core_profiles_in

    # From TIP
    tip.interferometer_out: imas_rt_mapping.interferometer_in

    # From imas_rt_mapping
    imas_rt_mapping.pellets_out: smart.pellets_in
    imas_rt_mapping.line_avg_density_out: pelletController.line_avg_density_in # With PCSSP

    # From pelletController
    pelletController.pellets_trigger_request_out: imas_rt_mapping.pellets_trigger_request_in

settings:
    xml_path_tip: ../../../../input/tip.xml
    xml_path_smart: ../../../../input/smart.xml
    muscle_remote_log_level: DEBUG
    
resources:
  im_workflow:
    threads: 1
  smart:
    threads: 1
  tip:
    threads: 1
  imas_rt_mapping:
    threads: 1
  pelletController:
    threads: 1  

implementations:
   im_workflow:
     executable: python #xterm -e
     args: -u ../../../../im_workflow.py
   tip:
     executable: python
     args: -u ../../../../muscled_tip.py
   smart:
     executable: python
     args: -u ../../../../muscled_smart.py
   imas_rt_mapping:
     executable: python
     args: -u ../../../../imas_rt_mapping.py
   pelletController:
     executable: matlab
     args: -batch "cd ../../../../, run('pelletController_init.m')"  
```
